name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.46.0
        with: 
          ruby-version: 3.0
      
      - uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install
      
      - name: Install Dependencies
        run: |
          gem install bundler
      - name: Install Gems
        run: |
          bundle install
      - name: Prepare Database
        run: |
          bundle exec rails db:migrate
      - name: Run Tests
        run: |
          bundle exec rails test
  
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.46.0
        with: 
          ruby-version: 3.0

      - name: Install Brakeman
        run: |
          gem install brakeman
      - name: Run Brakeman
        run: |
          brakeman -f json > tmp/brakeman.json || exit 0
      - name: Brakeman Report
        uses: devmasx/brakeman-linter-action@v1.0.0
        env:
          REPORT_PATH: tmp/brakeman.json
          GITHUB_TOKEN: ${{ secrets.RAILS_MASTER_KEY }}

